### ISSUE TITLE
Fatal errors due to magic methods (__get, __set, etc.)

### ISSUE THREAD

**Issue by crossbap** [BapCat/Facade#5]
We are currently outputting static method definitions for magic methods (e.g. __get(), __set(), and __isset()), but these are causing PHP to fatal error.  I suggest we do not output any methods starting with double-underscore, as those are [reserved by PHP for methods that are "magical"](http://php.net/manual/en/language.oop5.magic.php).

```
2018-06-10 07:53:25 Warning: PHP Warning (2): The magic method __get() must have public visibility and cannot be static in [.../facades/Facade.php.f8576eb3449f852cd478761fde12e2db1055993c.php line 56]

PHP Fatal error:  Method Config::__get() must take exactly 1 argument in .../facades/Facade.php.f8576eb3449f852cd478761fde12e2db1055993c.php on line 57
```

**Comment by LordMonoxide** [comment]
Good idea. I'll get a PR up for this shortly.

Sent from my Windows 10 phone

From: Ross Campbell
Sent: June 10, 2018 22:16
To: BapCat/Facade
Cc: Subscribed
Subject: [BapCat/Facade] Fatal errors due to magic methods (__get, __set,etc.) (#5)

We are currently outputting static method definitions for magic methods (e.g. __get(), __set(), and __isset()), but these are causing PHP to fatal error. I suggest we do not output any methods starting with double-underscore, as those are reserved by PHP for methods that are "magical".
2018-06-10 07:53:25 Warning: PHP Warning (2): The magic method __get() must have public visibility and cannot be static in [.../facades/Facade.php.f8576eb3449f852cd478761fde12e2db1055993c.php line 56]

PHP Fatal error:  Method Config::__get() must take exactly 1 argument in .../facades/Facade.php.f8576eb3449f852cd478761fde12e2db1055993c.php on line 57
